### ISSUE TITLE
Injecting a mapper in a servlet filter fails

### ISSUE THREAD

**Issue by raupachz** [mybatis/cdi#42]
Hello,

for some reason injecting a mapper in a Servlet Filter fails. The filter is annotated with @WebFilter. I can inject other stuff with @Inject. For example a SqlSessionFactory. That works without problems. If I however try to do a @Inject @Mapper it end up with a unsatisfied dependency exception. 

I can inject mappers in other JSF beans. So everything with @Named and a scope is fine. Only the servlet filter is causing trouble. 

**Versions:**
Servlet API 3.1
Weld 2.3.5.Final
Mybatis 3.4.1
Mybatis-CDI 1.0.0-beta3

**Exception:**
30-Aug-2016 09:48:29.532 SEVERE [http-nio-8080-exec-7] org.apache.catalina.core.StandardContext.filterStart Exception starting filter de.e2n.gastroapp.perso.servlet.filter.CookieFilter
 org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type CookieMapper with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject @Mapper private de.e2n.gastroapp.perso.servlet.filter.CookieFilter.cookieMapper
  at de.e2n.gastroapp.perso.servlet.filter.CookieFilter.cookieMapper(CookieFilter.java:0)

```
at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:359)
at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:281)
at org.jboss.weld.bootstrap.Validator.validateProducer(Validator.java:417)
at org.jboss.weld.injection.producer.InjectionTargetService.validateProducer(InjectionTargetService.java:36)
at org.jboss.weld.injection.producer.WeldInjectionTargetBuilderImpl.run(WeldInjectionTargetBuilderImpl.java:100)
at org.jboss.weld.injection.producer.WeldInjectionTargetBuilderImpl.build(WeldInjectionTargetBuilderImpl.java:93)
at org.jboss.weld.environment.servlet.inject.AbstractInjector$1.load(AbstractInjector.java:54)
at org.jboss.weld.environment.servlet.inject.AbstractInjector$1.load(AbstractInjector.java:47)
at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
at org.jboss.weld.util.cache.LoadingCacheUtils.getCacheValue(LoadingCacheUtils.java:49)
at org.jboss.weld.util.cache.LoadingCacheUtils.getCastCacheValue(LoadingCacheUtils.java:74)
at org.jboss.weld.environment.servlet.inject.AbstractInjector.inject(AbstractInjector.java:60)
at org.jboss.weld.environment.tomcat.WeldInstanceManager.newInstance(WeldInstanceManager.java:25)
at org.jboss.weld.environment.tomcat.WeldForwardingInstanceManager.newInstance(WeldForwardingInstanceManager.java:72)
at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:258)
at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:105)
at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4561)
at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5204)
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:152)
at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:724)
at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:700)
at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:596)
at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:467)
at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1617)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:300)
at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
at org.apache.catalina.manager.ManagerServlet.check(ManagerServlet.java:1483)
at org.apache.catalina.manager.ManagerServlet.deploy(ManagerServlet.java:904)
at org.apache.catalina.manager.ManagerServlet.doGet(ManagerServlet.java:336)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:108)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:632)
at org.apache.catalina.valves.RequestFilterValve.process(RequestFilterValve.java:319)
at org.apache.catalina.valves.RemoteAddrValve.invoke(RemoteAddrValve.java:88)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:1110)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:785)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1425)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:745)
```

**Comment by raupachz** [comment]
If I add @Dependent to the servlet filter it looks like it is working. I am just not sure if this is correct. Don't know that much about @Dependent scope.

**Comment by hazendaz** [comment]
@dependent in my understanding means the object doesnt live on its own with a scope.  Not sure if that makes sense here either.  I was going to suggest to use latest snapshot to see if there is any difference.

Get Outlook for Android<https://aka.ms/ghei36>



On Tue, Aug 30, 2016 at 4:06 AM -0400, "Björn Raupach" <notifications@github.com<mailto:notifications@github.com>> wrote:


If I add @Dependent<https://github.com/Dependent> to the servlet filter it looks like it is working. I am just not sure if this is correct. Don't know that much about @Dependent<https://github.com/Dependent> scope.

-

**Comment by raupachz** [comment]
@hazendaz Could you give me the link to the snapchat repository. I would try.

**Comment by hazendaz** [comment]
@raupachz sorry for the delay.  Our automated builds for snapshots looks like it's not hooked up on this project.  I manualy pushed out the latest.  You can find it [here](https://oss.sonatype.org/content/repositories/snapshots/org/mybatis/mybatis-cdi/1.0.0-beta4-SNAPSHOT/)

**Comment by raupachz** [comment]
Sorry for the late reply. I have no clue if it worked or not. Need to check this again. I totally forgot about it.

**Comment by mnesarco** [comment]
Hi Guys, any news on this?

**Comment by mnesarco** [comment]
Hi @raupachz there is a beta5 now in maven central. Can you give it a try?

**Comment by mnesarco** [comment]
I have tested beta5 against Payara 4.1 (Glassfish 4.1) and TomEE-Plus 7.0.1
Please take a look at: https://github.com/mnesarco/mybatis-cdi-samples
