### ISSUE TITLE
issue with micro profile standard

### ISSUE THREAD

**Issue by surajchhetry** [mybatis/cdi#81]
Hi,
When I use mybatis-cdi with full JEE 7 app server it is working fine without any issue.But when I use microprofile like kumuluz I am getting following exception 
```
 Caused by: java.lang.RuntimeException: javax.naming.NameNotFoundException; remaining name 
 'BeanManager'
	at org.mybatis.cdi.CDIUtils.getBeanManager(CDIUtils.java:67)
	at org.mybatis.cdi.CDIUtils.findSqlSessionFactory(CDIUtils.java:94)
	at org.mybatis.cdi.SerializableMapperProxy.getMapper(SerializableMapperProxy.java:63)
	at org.mybatis.cdi.SerializableMapperProxy.<init>(SerializableMapperProxy.java:50)
	at org.mybatis.cdi.MyBatisBean.create(MyBatisBean.java:124)
	at org.jboss.weld.context.unbound.DependentContextImpl.get(DependentContextImpl.java:70)
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
	at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:786)
```
I fixed this by replacing below method 

```
private static BeanManager getBeanManager() {
    try {
      return InitialContext.doLookup(JNDI.NAME);
    } catch (NamingException e) {
      throw new RuntimeException(e);
    }
  }
```
With 
```
 private static BeanManager getBeanManager() {
    return CDI.current().getBeanManager();
  }
```
since CDI utility is only available CDI 1.1+ .

**Comment by mnesarco** [comment]
Hi @surajchhetry ,
Can you please take a look at this. I have just committed a fix. All tests passed, but I don't have your environment so if you can test it would be great.
